name: golang pkg starter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-ctrd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - run: mkdir -p /home/runner/go/{src/github.com/ModEtchFill,cover}
      - run: ln -s /home/runner/work/base-i/base-i /home/runner/go/src/github.com/ModEtchFill
      - name: Build
        run: go build -v ./...
      - name: Test a
        run: go test -v -coverprofile /home/runner/go/cover/a github.com/ModEtchFill/base-i/aTest
      - name: Test b
        run: go test -v -coverprofile /home/runner/go/cover/b github.com/ModEtchFill/base-i/bTest
      - name: Cov
        run: go tool covdata percent -i=/home/runner/go/cover
