name: golang pkg starter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-ctrd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Manual go1.20
        run: wget -nv https://go.dev/dl/go1.20.7.linux-amd64.tar.gz
      - run: sed -e 's,http.*/,,' SHA256 | sha256sum -c
      - run: tar zxfv go1.20.7.linux-amd64.tar.gz
      - run: pwd
      - name: End - Manual go1.20
        run: /home/runner/go/bin/go version

      - name: Setup github go paths for proper library locations
        run: mkdir -p /home/runner/go/{src/github.com/ModEtchFill,cover}
      - name: End - Setup github go paths
        run: ln -s /home/runner/work/base-i/base-i /home/runner/go/src/github.com/ModEtchFill

      - name: Build
        run: /home/runner/go/bin/go build -v ./...
      - name: Test a
        run: /home/runner/go/bin/go test -v -coverprofile /home/runner/go/cover/a github.com/ModEtchFill/base-i/aTest
      - name: Test b
        run: /home/runner/go/bin/go test -v -coverprofile /home/runner/go/cover/b github.com/ModEtchFill/base-i/bTest
      - name: Cov
        run: /home/runner/go/bin/go tool covdata percent -i=/home/runner/go/cover
